export type cityCodesObjectOfTuples = [number, string]

export enum plateIdentifier {
    WHLCH = "معلول",
    ALEF = "الف",
    BE = "ب",
    PE = "پ",
    TE = "ت",
    SE = "ث",
    JIM = "ج",
    CHE = "چ",
    HE_JIMI = "ح",
    KHE = "خ",
    DAL = "د",
    ZAL = "ذ",
    RE = "ر",
    ZE = "ز",
    JE = "ژ",
    SIN = "س",
    SHIN = "ش",
    SAD = "ص",
    ZAD = "ض",
    TA = "ط",
    ZA = "ظ",
    AYN = "ع",
    GHAYN = "غ",
    FE = "ف",
    QAF = "ق",
    KAF = "ک",
    GAF = "گ",
    LAM = "ل",
    MIM = "م",
    NUN = "ن",
    VAV = "و",
    HE = "ه",
    YE = "ی"
}